variables:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

pages:
  image: 
    name: registry.gitlab-simplon.akiros.school/thomas/stopify-landing-page-docker:main
    entrypoint: [""]
  script:
    - hugo --minify -e gl-pages -s website -d ../public
  artifacts:
    paths:
      - public
  except:
    refs:
      - main

aws:
  image: 
    name: registry.gitlab-simplon.akiros.school/thomas/stopify-landing-page-docker:main
    entrypoint: [""]
  script:
    - hugo --minify -e s3 -s website
    - hugo deploy --force --maxDeletes -1 --invalidateCDN -e s3 -s website
  only:
    refs:
      - main
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
