title = "Stopify"
theme = "bigspring"
defaultContentLanguage = "fr"
paginate = "3"
summaryLength = "15"

[deployment]

[[deployment.targets]]
name = "awss3"
URL = "s3://stopify-20210714175905446300000001?region=eu-west-3"
